### ISSUE TITLE
Clear the route from my screen 

### ISSUE THREAD

**Issue by mdiener21** [indrz/indrz#13]
If a route is generated the user needs the ability to remove the route, aka clear route from screen

**Comment by devstorm21** [comment]
@mdiener21 what interface do we need for the ability? "Clear" button or what?

**Comment by mdiener21** [comment]
@devstorm21  Please add a button beside the current Go!  button that should only show up AFTER a route is created.   Once a route is drawn on screen the button shows up and a user can click this button removing the route from the map completely (not hiding) then user can create a new route and the button disappears when NO route is shown.
