### ISSUE TITLE
share a map url

### ISSUE THREAD

**Issue by mdiener21** [indrz/indrz#21]
related to #16 
click share map button and user will see a Bootstrap modal popup showing the current map URL highlighted and copied to users clip board for sharing. When the url is opened in a new window the user is taken to that exact extent and zoom level shared in the link.

share a map shares the current map extent and zoom level as  a link for a user to copy and paste, the URL should also be small and short

**Comment by devstorm21** [comment]
@mdiener21  Copy the url to the user's clipboard requires the flash player plugin on the browser. Would it be okay?

**Comment by mdiener21** [comment]
@devstorm21  no flash  if not allowed by browser then simply select the text ie the url using javascript so the user can see the url is selected

**Comment by mdiener21** [comment]
@devstorm21   page not found error when trying to open the share link
