### ISSUE TITLE
share search result

### ISSUE THREAD

**Issue by mdiener21** [indrz/indrz#23]
if a user searches for a room for example and finds room D1.2.300 this result is shareable.  The share link will be created and the user can copy paste the link.  Upon opening the link the map will zoom to the result and show it as active, open the map popup

**Comment by mdiener21** [comment]
@devstorm21  not working as expected the link page not found error and room not activated

**Comment by devstorm21** [comment]
@mdiener21 which room is it? It might not be found on the search result.
