### ISSUE TITLE
can you upload the demo geodata?

### ISSUE THREAD

**Issue by gischy** [indrz/indrz#42]

**Comment by mdiener21** [comment]
Hi sorry nobody has contributed free open data to publish.  All of the current organizations have not released their data for public use, really sorry, would love to publish some.  Maybe soon  I hope :)  you can check out my book and code with some geodata :)  https://github.com/mdiener21/python-geospatial-analysis-cookbook

**Comment by gischy** [comment]
Hey,

I have tried to create a simple route network. I followed the tutorial steps. Im wondering why it is possible to route over different floors without having placed any stairs or elevators in the network lines. I have two layers with route network lines having the two attributes type "indoor way" and type_id "0". Currently just facing the problem that different layers get connected at intersecting floor route points of indoor ways.
