### ISSUE TITLE
share map url on open new url  centerx and center y  NaN in url

### ISSUE THREAD

**Issue by mdiener21** [indrz/indrz#69]
when a users copies the map share url into a new window and opens the window the new url automatically updates as NaN for centerx and centery

**Comment by mdiener21** [comment]
@devstorm21   is it possible that you fix this bug I found in your share map function

**Comment by devstorm21** [comment]
@mdiener21 possible. Could you give me 5 marks in upwork before fixing it? I will appreciate if you do and we can build a good relationship.

**Comment by mdiener21** [comment]
@devstorm21  contact me via skype

**Comment by mdiener21** [comment]
line 2 of  indrz_live_url_update.js  calling update_url()   is the problem
